services:
  nats_server:
    container_name: nats_server
    image: nats
    ports:
      - 8222:8222

  client_gateway:
    container_name: client_gateway
    build: ./client_gateway
    ports:
      - 3333:3333
    volumes:
      - ./client_gateway/src:/usr/src/app/src
    command: pnpm start:dev
    env_file:
      - ./client_gateway/.env

  products_ms:
    container_name: products_ms
    build: ./products_ms
    command: sh -c "pnpm prisma migrate deploy && pnpm prisma generate && pnpm start:dev"
    ports:
      - 5556:5555
    volumes:
      - ./products_ms/src:/usr/src/app/src
    env_file:
      - ./products_ms/.env

  orders_ms:
    container_name: orders_ms
    build: ./orders_ms
    command: sh -c "pnpm prisma migrate deploy && pnpm prisma generate && pnpm start:dev"
    ports:
      - 5557:5555
    volumes:
      - ./orders_ms/src:/usr/src/app/src
    env_file:
      - ./orders_ms/.env
    depends_on:
      - order_db

  order_db:
    container_name: orders_db
    image: postgres:16.2
    volumes:
      - ./orders_ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db

  payments_ms:
    container_name: payments_ms
    build: ./payments_ms
    command: sh -c "pnpm start:dev"
    ports:
      - 3003:3003
    volumes:
      - ./payments_ms/src:/usr/src/app/src
    env_file:
      - ./payments_ms/.env

  auth_ms:
    container_name: auth_ms
    build: ./auth_ms
    command: sh -c "pnpm start:dev"
    ports:
      - 5558:5555
    volumes:
      - ./auth_ms/src:/usr/src/app/src
    env_file:
      - ./auth_ms/.env
